### ISSUE TITLE
Outline of my thesis

### ISSUE THREAD

**Issue by yipengsun** [yipengsun/umd_phd_thesis#1]
Outline (updated):

- [x] Introduction

## Part I
- [x] Analysis overview
- [x] Theory of semitauonic B decays
- [x] LHCb detector
- [x] Event selection
- [x] Correction and validation of the MC simulation
- [x] Signal extraction fit
- [x] Systematic uncertainties
~~Aside: reproducible analysis~~
- [x] Conclusion

## Part II
- [x] Overview of LHCb upgrade
- [x] UT upgrade

**Comment by yipengsun** [comment]
Remove less important chapter. I cannot be to ambitious.

**Comment by yipengsun** [comment]
Finally done.
